from enum import Enum
from dataclasses import dataclass
from typing import Dict

class Symbol(Enum):
    # deribit most common symbols
    BROWNIAN = 'BROWNIANUSDT' #lets assume we have a brownian motion data generated by the brownian.py script
    BTC = 'BTCUSDT'
    ETH = 'ETHUSDT'
    SOL = 'SOLUSDT'
    XRP = 'XRPUSDT'
    ADA = 'ADAUSDT'
    DOT = 'DOTUSDT'
    LINK = 'LINKUSDT'
    BCH = 'BCHUSDT'
    LTC = 'LTCUSDT'
    DOGE = 'DOGEUSDT'

    @staticmethod
    def get_all_symbols():
        return list(Symbol)

@dataclass
class SymbolConfig:
    ticksize: float

# Symbol-specific configurations
# Add a minimal quantity if you want
SYMBOL_CONFIGS: Dict[Symbol, SymbolConfig] = {
    Symbol.BTC: SymbolConfig(
        ticksize=1.0,
    ),
    Symbol.ETH: SymbolConfig(
        ticksize=0.5,
    ),
    Symbol.BROWNIAN: SymbolConfig(
        ticksize=1.0,
    )
}

# Default values for parameters that are common across symbols
# Simulation does not allow for multiple timeframes at once
maker_fee = 0.0002
taker_fee = 0.0005
DEFAULT_PARAMS = {
    'initial_cash': 100000,
    'maker_fee': maker_fee,  # Lower fee for limit orders that provide liquidity
    'taker_fee': taker_fee,  # Higher fee for market orders that take liquidity
    'minimal_spread': 4*maker_fee, # 2*maker_fee is the absolute minimum spread you can have otherwise you will lose money at each trade
    
    'valid_periods': ['1', '3', '5', '15', '30', '60', '120', '240', '360', '720', '1d'],
    'default_window' : 14, #default window length for any indicator when not specified
    'data_size' : -1,# debug parameter, to be removed later : on how many data points to run the simulation, if - 1 : all the data
    # Risk management parameters
    'max_leverage': 1.0,  # Maximum allowed total leverage accross all symbols (when opening new positions)
    'aggressivity': 0.1, # at each timestamp the total new buy or total new sell order cannot exceed
    # max_leverage*aggressivity (small aggresivity builds slowly the position like a grid bot would)
    'emergency_exit_leverage': 2,  # Total leverage level that triggers emergency exit
    'early_stopping_margin': 0.1, # stop simulation if margin ratio is less than 10% of initial margin
    'min_order_value_usd': 10.0,  # Minimum order value in USD
}

